[env]
TERM = "xterm-256color"

[terminal]
shell = "/bin/zsh"

[window]
dimensions = { columns = 150, lines = 48 }
padding = { x = 5, y = 5}
decorations = "Full"
opacity = 0.90
blur = true
decorations_theme_variant = "None"
option_as_alt = "OnlyLeft"

[scrolling]
history = 50000

[font]
size = 11.25

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 750
blink_timeout = 180
