[env]
TERM = "xterm-256color"

[terminal]
shell = "/bin/zsh"

[window]
dimensions = { columns = 150, lines = 48 }
padding = { x = 1, y = 1}
decorations = "Full"
opacity = 0.90
blur = false
decorations_theme_variant = "None"
option_as_alt = "OnlyLeft"

[scrolling]
history = 50000

[font]
normal = { family = "Source Code Pro", style = "Regular" }
size = 11.25

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 750
blink_timeout = 180
